spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Rental Management System REST API
  profiles:
      active: ${APP_PROFILE:prod}
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:rent_mgmt_db}
    username: ${DB_USER:root}
    password: ${DB_PASS:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
  output:
    ansi:
      enabled: always
server:
  port: 8080

springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: alpha

#management:
#  endpoints:
#    web:
#      exposure:
#        include: *