spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Rental Management System REST API
  profiles:
      active: dev
  datasource:
    url: jdbc:mysql://localhost:3307/rental_management
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
  output:
    ansi:
      enabled: always
server:
  port: 8080

springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: alpha
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *