spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  devtools:
    restart:
      enabled: true

logging:
  level:
    org.springframework: debug
    org.hibernate.orm.jdbc.bind: TRACE # shows the actual parameter values
    com.rental.rental_management_api: debug

springdoc:
  swagger-ui:
    tryItOutEnabled: true