spring:
  sql:
    init:
      mode: never
  jpa:
    show-sql: false

logging:
  level:
    org.springframework: info
    com.rental.rental_management_api: info

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false