spring:
  sql:
    init:
      mode: never
  jpa:
    show-sql: false

logging:
  level:
    org:
      springframework: info


springdoc:
  swagger-ui:
    tryItOutEnabled: false
    supportedSubmitMethods: []